name: Vuepress Deploy
on: 
  push:
    branches:
      - master
      - next
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: src/.vitepress/dist
