name: Vuepress Deploy
on: 
  push:
    branches:
      - master
      - deploy-test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-verions: '14'

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: npm install

    - name: vite build
      run: npm run build

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: src/.vuepress/dist/
